define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.loaded = 'loaded';
    exports.load = 'load';
    exports.animationComplete = 'animationComplete';
    exports.legendRender = 'legendRender';
    exports.textRender = 'textRender';
    exports.pointRender = 'pointRender';
    exports.seriesRender = 'seriesRender';
    exports.axisLabelRender = 'axisLabelRender';
    exports.tooltipRender = 'tooltipRender';
    exports.chartMouseMove = 'chartMouseMove';
    exports.chartMouseClick = 'chartMouseClick';
    exports.chartMouseLeave = 'chartMouseLeave';
    exports.chartMouseDown = 'chartMouseDown';
    exports.chartMouseUp = 'chartMouseUp';
    exports.zoomComplete = 'zoomComplete';
    exports.dragComplete = 'dragComplete';
});
